// examples/starters/svelte/src/App.svelte
<script lang="ts">
  import type { KaiResizableItemElement } from '@kitn.ai/ui/elements';
  import { readOpenAIStream } from '@kitn.ai/ui/wire';
  import { CONVERSATIONS, THREADS, SUGGESTIONS, TRIGGERS, newId, mockResponse } from './chat-data';
  import type { Theme } from './lib/types';
  import { createChat } from './lib/chat.svelte';
  import { createConversations } from './lib/conversations.svelte';
  import Sidebar from './components/Sidebar.svelte';
  import ThreadView from './components/ThreadView.svelte';
  import Composer from './components/Composer.svelte';
  import ThemeToggle from './components/ThemeToggle.svelte';

  /**
   * A mini chat workspace COMPOSED BY HAND from @kitn.ai/ui's individual elements —
   * the Svelte mirror of `examples/react` + `examples/vue`. It shows how the raw
   * `kai-*` web components fit together (vs. dropping in one batteries-included
   * `<kai-chat>`/`<kai-workspace>`):
   *
   *   <kai-resizable>/<kai-resizable-item>  — the draggable sidebar | main split (the
   *                                           divider is the kit's default `line` hairline)
   *   <kai-conversations>  — the sidebar list (fed `conversations`, emits select/new)
   *   <kai-thread>         — the scrolling message list (stick-to-bottom built in)
   *   <kai-prompt-input>   — the composer at the bottom
   *
   * The pieces are split into `components/` (the UI subcomponents + the example's own
   * moon/sun icons) and `lib/` (`createChat` owns the message array + streaming,
   * `createConversations` the conversation stash, `createVoiceInput` the mic).
   * Everything else is plain Svelte runes. Swap `mockResponse(text)` for a real
   * `fetch` to ship.
   */
  let theme: Theme = $state('dark');
  let collapsed = $state(false);
  const chat = createChat(THREADS[CONVERSATIONS[0].id] ?? []);
  const conversations = createConversations(chat, CONVERSATIONS);

  const suggestions: string[] = $derived(chat.messages.length <= 1 ? SUGGESTIONS : []);

  // The sidebar <kai-resizable-item>'s `collapsed` boolean is a DOM property the
  // parent <kai-resizable> reads (reflected to an attribute the group observes), so
  // drive it imperatively rather than as a bare attribute.
  let sidebarItem: KaiResizableItemElement;
  $effect(() => { sidebarItem.collapsed = collapsed; });

  async function send(raw: string) {
    const text = raw.trim();
    if (!text) return;
    // The Composer already cleared its own input; here we just append the user
    // message and stream the (mock) assistant reply.
    chat.append({ id: newId(), role: 'user', parts: [{ type: 'text', text }] });
    const stream = chat.streamAssistant();
    // NO BACKEND AND NO PROVIDER. mockResponse() yields canned SSE frames that go
    // through the SAME reader a real model's response would, so this preview
    // exercises the real path. To go live, only this one expression changes —
    // `mockResponse(text)` becomes a POST to your route, with
    // toOpenAIMessages(chat.messages) as the body. The line below stays.
    await readOpenAIStream(mockResponse(text), stream);
    stream.done();
  }
</script>

<!-- <kai-resizable> owns the sidebar width + the divider. The handle defaults to the
     `line` hairline (transparent at rest, tinting on hover/drag); collapsing the
     sidebar maps to <kai-resizable-item collapsed>. Pass `theme` to the group AND
     every item so slotted chrome inherits the right light/dark tokens. -->
<div class="app" class:dark={theme === 'dark'}>
  <kai-resizable {theme} orientation="horizontal">
    <kai-resizable-item bind:this={sidebarItem} {theme} size="280px" min="220px" max="420px">
      <Sidebar
        {theme}
        conversations={conversations.conversations}
        activeId={conversations.activeId}
        {collapsed}
        onselect={conversations.selectConversation}
        onnewchat={conversations.newChat}
        ontoggle={() => (collapsed = !collapsed)}
      />
    </kai-resizable-item>

    <kai-resizable-item {theme}>
      <main class="main">
        <header class="bar">
          <div class="bar-left">
            {#if collapsed}
              <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
              <kai-button
                {theme}
                variant="ghost"
                size="icon"
                icon="panel-left"
                label="Show sidebar"
                onclick={() => (collapsed = false)}
              ></kai-button>
            {/if}
            <span class="brand">@kitn.ai/ui · composed chat</span>
          </div>
          <ThemeToggle {theme} ontoggle={() => (theme = theme === 'light' ? 'dark' : 'light')} />
        </header>

        <ThreadView {theme} messages={chat.messages} />

        <Composer
          {theme}
          loading={chat.loading}
          {suggestions}
          triggers={TRIGGERS}
          onsubmit={send}
          onsuggestion={send}
        />
      </main>
    </kai-resizable-item>
  </kai-resizable>
</div>

// examples/starters/vue/src/App.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { readOpenAIStream } from '@kitn.ai/ui/wire';
import { CONVERSATIONS, THREADS, SUGGESTIONS, TRIGGERS, newId, mockResponse } from './chat-data';
import type { Theme } from './types';
import { useChat, useConversations } from './composables';
import Sidebar from './components/Sidebar.vue';
import ThreadView from './components/ThreadView.vue';
import Composer from './components/Composer.vue';
import ThemeToggle from './components/ThemeToggle.vue';

/**
 * A mini chat workspace COMPOSED BY HAND from @kitn.ai/ui's individual elements —
 * the Vue mirror of `examples/react`. It shows how the raw `kai-*` web components
 * fit together (vs. dropping in one batteries-included `<kai-chat>`/`<kai-workspace>`):
 *
 *   <kai-resizable>/<kai-resizable-item>  — the draggable sidebar | main split (the
 *                                           divider is the kit's default `line` hairline)
 *   <kai-conversations>  — the sidebar list (fed `conversations`, emits select/new)
 *   <kai-thread>         — the scrolling message list (stick-to-bottom built in)
 *   <kai-prompt-input>   — the composer at the bottom
 *
 * The pieces are split into `components/` (the UI subcomponents + the example's own
 * moon/sun icons) and `composables/` (`useChat` owns the message array + streaming,
 * `useConversations` the conversation stash, `useVoiceInput` the mic). Everything
 * else is plain Vue refs. Swap `mockResponse(text)` for a real `fetch` to ship.
 */
const theme = ref<Theme>('dark');
const collapsed = ref(false);
const chat = useChat(THREADS[CONVERSATIONS[0].id] ?? []);
const { messages, loading } = chat;
const { conversations, activeId, selectConversation, newChat } = useConversations(chat, CONVERSATIONS);

const suggestions = computed(() => (messages.value.length <= 1 ? SUGGESTIONS : []));

async function send(raw: string) {
  const text = raw.trim();
  if (!text) return;
  // The Composer already cleared its own input; here we just append the user
  // message and stream the (mock) assistant reply.
  chat.append({ id: newId(), role: 'user', parts: [{ type: 'text', text }] });
  const stream = chat.streamAssistant();
  // NO BACKEND AND NO PROVIDER. mockResponse() yields canned SSE frames that go
  // through the SAME reader a real model's response would, so this preview
  // exercises the real path. To go live, only this one expression changes —
  // `mockResponse(text)` becomes a POST to your route, with
  // toOpenAIMessages(messages.value) as the body. The line below stays.
  await readOpenAIStream(mockResponse(text), stream);
  stream.done();
}
</script>

<template>
  <div class="app" :class="{ dark: theme === 'dark' }">
    <!-- <kai-resizable> owns the sidebar width + the divider. The handle defaults to
         the `line` hairline (transparent at rest, tinting on hover/drag); collapsing
         the sidebar maps to <kai-resizable-item :collapsed>. Pass `theme` to the group
         AND every item so slotted chrome inherits the right light/dark tokens. -->
    <kai-resizable :theme="theme" orientation="horizontal">
      <kai-resizable-item :theme="theme" size="280px" min="220px" max="420px" :collapsed.prop="collapsed">
        <Sidebar
          :theme="theme"
          :conversations="conversations"
          :active-id="activeId"
          :collapsed="collapsed"
          @select="selectConversation"
          @new-chat="newChat"
          @toggle="collapsed = !collapsed"
        />
      </kai-resizable-item>

      <kai-resizable-item :theme="theme">
        <main class="main">
          <header class="bar">
            <div class="bar-left">
              <kai-button
                v-if="collapsed"
                :theme="theme"
                variant="ghost"
                size="icon"
                icon="panel-left"
                label="Show sidebar"
                @click="collapsed = false"
              ></kai-button>
              <span class="brand">@kitn.ai/ui · composed chat</span>
            </div>
            <ThemeToggle :theme="theme" @toggle="theme = theme === 'light' ? 'dark' : 'light'" />
          </header>

          <ThreadView :theme="theme" :messages="messages" />

          <Composer
            :theme="theme"
            :loading="loading"
            :suggestions="suggestions"
            :triggers="TRIGGERS"
            @submit="send"
            @suggestion="send"
          />
        </main>
      </kai-resizable-item>
    </kai-resizable>
  </div>
</template>
