// examples/starters/vue/src/components/ThreadView.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { ChatMessage } from '@kitn.ai/ui';
import { partsToText } from '@kitn.ai/ui/state';
import type { Theme } from '../types';

/**
 * The scrolling message list. `<kai-thread>` owns the message rendering, the
 * centered fixed-width column, and stick-to-bottom scroll, so this component just
 * bakes the per-message actions onto the assistant turns and wires the custom
 * `speak` action to the browser's speech synthesis. `copy` (and the feedback
 * votes) are handled inside the element.
 *
 * `messages` is passed to the element as a DOM PROPERTY (`.prop`); a NEW array
 * reference per streaming chunk is what re-renders it. The `withActions` computed
 * derives that fresh array whenever `messages` changes.
 */
const props = defineProps<{
  theme: Theme;
  messages: ChatMessage[];
}>();

// <kai-thread> reads `actions` off each message; only assistant replies get them.
const withActions = computed<ChatMessage[]>(() =>
  props.messages.map((m) =>
    m.role === 'assistant'
      ? { ...m, actions: ['copy', { id: 'speak', label: 'Read aloud', icon: 'volume-2' }] }
      : m,
  ),
);

function onMessageAction(e: Event) {
  const detail = (e as CustomEvent<{ messageId: string; action: string }>).detail;
  if (detail.action === 'speak') {
    const m = props.messages.find((x) => x.id === detail.messageId);
    if (!m) return;
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(new SpeechSynthesisUtterance(partsToText(m.parts)));
  }
}
</script>

<template>
  <kai-thread
    class="thread"
    :theme="theme"
    :messages.prop="withActions"
    @kai-message-action="onMessageAction"
  ></kai-thread>
</template>

// examples/starters/react/src/components/ThreadView.tsx
import { Thread } from '@kitn.ai/ui/react';
import type { ChatMessage } from '@kitn.ai/ui/react';
import { partsToText } from '@kitn.ai/ui/state';
import type { Theme } from '../App';

interface ThreadViewProps {
  theme: Theme;
  messages: ChatMessage[];
}

/**
 * The scrolling message list. `<kai-thread>` (React `<Thread>`) owns the message
 * rendering, the centered fixed-width column, and stick-to-bottom scroll, so this
 * component just bakes the per-message actions onto the assistant turns and wires
 * the custom `speak` action to the browser's speech synthesis. `copy` (and the
 * feedback votes) are handled inside the element.
 */
export function ThreadView({ theme, messages }: ThreadViewProps) {
  // <Thread> reads `actions` off each message; only assistant replies get them.
  const withActions: ChatMessage[] = messages.map((m) =>
    m.role === 'assistant'
      ? { ...m, actions: ['copy', { id: 'speak', label: 'Read aloud', icon: 'volume-2' }] }
      : m,
  );
  return (
    <Thread
      className="thread"
      theme={theme}
      messages={withActions}
      onMessageAction={(e) => {
        if (e.detail.action === 'speak') {
          const m = messages.find((x) => x.id === e.detail.messageId);
          if (!m) return;
          window.speechSynthesis.cancel();
          window.speechSynthesis.speak(new SpeechSynthesisUtterance(partsToText(m.parts)));
        }
      }}
    />
  );
}
