// examples/starters/angular/src/app/components/composer/composer.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, ElementRef, ViewChild, input, output } from '@angular/core';
import type { Theme } from '../../types';
import { useVoiceInput } from '../../state/voice-input';

/** The imperative surface of <kai-prompt-input> this composer drives. */
type PromptInputEl = HTMLElement & { value?: unknown; clear?: () => void };

/**
 * The bottom composer. Wraps `<kai-prompt-input>` and owns the input-DOM concerns:
 * the element ref, a live text mirror, clear-on-submit, and seeding voice.
 *
 * The prompt input stays UNCONTROLLED so the `/`+`@` trigger menus keep a live
 * caret. We NEVER bind `[value]` with a plain STRING: that flips the element into
 * controlled mode, which re-applies the property and collapses the shadow-DOM
 * selection, disabling the caret-anchored menu. So clear-on-submit goes through the
 * element's `clear()` method, and voice seeds a ComposerDoc (a non-string value is a
 * one-time seed that leaves the input uncontrolled). We keep the live text mirrored
 * in `liveText` (from `kai-value-change`) so voice can append.
 *
 * `voice` is set as a truthy PROPERTY (`[voice]="true"`) because the facade's flag()
 * takes an explicit JS `false` over a present attribute, so the bound property is the
 * one that can still turn the flag back off. A bare `voice` attribute would also read
 * as TRUE here — presence is what counts, and only `voice="false"` reads as false.
 */
@Component({
  selector: 'app-composer',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './composer.html',
  styleUrl: './composer.css',
})
export class Composer {
  theme = input.required<Theme>();
  loading = input.required<boolean>();
  suggestions = input.required<string[]>();
  triggers = input.required<unknown[]>();

  submit = output<string>();
  suggestion = output<string>();

  // Ref to the underlying <kai-prompt-input> element for the imperative pushes
  // (clear() on submit, ComposerDoc seed from voice); `liveText` mirrors the text.
  @ViewChild('prompt', { static: true }) promptRef!: ElementRef<PromptInputEl>;
  private liveText = '';

  // Voice: on a transcript, append it to the current text and seed the (uncontrolled)
  // input as a ComposerDoc. A non-string `value` is a one-time seed into the
  // element's internal state; a plain STRING would instead flip it into controlled
  // mode and re-break the `/`+`@` triggers and submit.
  private readonly voice = useVoiceInput((transcript) => {
    const next = (this.liveText ? this.liveText + ' ' : '') + transcript;
    this.liveText = next;
    const el = this.promptRef?.nativeElement;
    if (el) el.value = [{ type: 'text', text: next }];
  });

  handleVoice() {
    // Mic is Chromium-only; degrade gracefully everywhere else.
    if (!this.voice.supported) {
      alert('Voice input needs a Chromium browser.');
      return;
    }
    this.voice.start();
  }

  onValueChange(e: Event) {
    this.liveText = (e as CustomEvent<{ value: string }>).detail.value;
  }

  onSubmit(e: Event) {
    // Clear our own uncontrolled input first — reset the mirror + call the element's
    // clear() method (uncontrolled-safe; fires kai-value-change internally, never a
    // string assignment) — then hand the text up. The parent owns append + streaming.
    this.liveText = '';
    this.promptRef?.nativeElement?.clear?.();
    this.submit.emit((e as CustomEvent<{ value: string }>).detail.value);
  }

  onSuggestionClick(e: Event) {
    this.suggestion.emit((e as CustomEvent<{ value: string }>).detail.value);
  }
}

// examples/starters/vue/src/components/Composer.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { KaiPromptInputElementProps } from '@kitn.ai/ui/elements';
import type { Theme } from '../types';
import { useVoiceInput } from '../composables';

/**
 * The bottom composer. Wraps `<kai-prompt-input>` and owns the input-DOM concerns:
 * the element ref, a live text mirror, clear-on-submit, and seeding voice.
 *
 * The prompt input stays UNCONTROLLED so the `/`+`@` trigger menus keep a live
 * caret. We NEVER bind `:value` with a plain STRING: that flips the element into
 * controlled mode, which re-applies the property and collapses the shadow-DOM
 * selection, disabling the caret-anchored menu. So clear-on-submit goes through
 * the element's `clear()` method, and voice seeds a ComposerDoc (a non-string
 * value is a one-time seed that leaves the input uncontrolled). We keep the live
 * text mirrored in `liveText` (from `kai-value-change`) so voice can append.
 */
defineProps<{
  theme: Theme;
  loading: boolean;
  suggestions: string[];
  // The kit owns this shape. Take it straight off the element's own prop type
  // (`@kitn.ai/ui/elements`) instead of re-declaring it here, so a change to the
  // trigger contract shows up as a build error rather than silent drift.
  triggers: NonNullable<KaiPromptInputElementProps['triggers']>;
}>();

const emit = defineEmits<{
  submit: [value: string];
  suggestion: [value: string];
}>();

// Ref to the underlying <kai-prompt-input> element for the imperative pushes
// (clear() on submit, ComposerDoc seed from voice); `liveText` mirrors the text.
const promptRef = ref<HTMLElement | null>(null);
let liveText = '';

// Voice: on a transcript, append it to the current text and seed the (uncontrolled)
// input as a ComposerDoc. A non-string `value` is a one-time seed into the
// element's internal state; a plain STRING would instead flip it into controlled
// mode and re-break the `/`+`@` triggers and submit.
const { supported: voiceSupported, start: startVoice } = useVoiceInput((transcript) => {
  const next = (liveText ? liveText + ' ' : '') + transcript;
  liveText = next;
  const el = promptRef.value as (HTMLElement & { value?: unknown }) | null;
  if (el) el.value = [{ type: 'text', text: next }];
});

function handleVoice() {
  // Mic is Chromium-only; degrade gracefully everywhere else.
  if (!voiceSupported) {
    alert('Voice input needs a Chromium browser.');
    return;
  }
  startVoice();
}

function onValueChange(e: Event) {
  liveText = (e as CustomEvent<{ value: string }>).detail.value;
}

function onSubmit(e: Event) {
  // Clear our own uncontrolled input first — reset the mirror + call the element's
  // clear() method (uncontrolled-safe; fires kai-value-change internally, never a
  // string assignment) — then hand the text up. The parent owns append + streaming.
  liveText = '';
  (promptRef.value as (HTMLElement & { clear?: () => void }) | null)?.clear?.();
  emit('submit', (e as CustomEvent<{ value: string }>).detail.value);
}

function onSuggestionClick(e: Event) {
  emit('suggestion', (e as CustomEvent<{ value: string }>).detail.value);
}
</script>

<template>
  <div class="composer">
    <kai-prompt-input
      ref="promptRef"
      :theme="theme"
      placeholder="Message the demo…"
      :loading="loading"
      :suggestions.prop="suggestions"
      :triggers.prop="triggers"
      :voice.prop="true"
      @kai-voice="handleVoice"
      @kai-value-change="onValueChange"
      @kai-submit="onSubmit"
      @kai-suggestion-click="onSuggestionClick"
    ></kai-prompt-input>
    <p class="composer-hint">
      Type <kbd>/</kbd> for skills · <kbd>@</kbd> for agents
    </p>
  </div>
</template>
