// examples/starters/react/src/components/Sidebar.tsx
import { Conversations } from '@kitn.ai/ui/react';
import type { Theme } from '../App';
import type { Conversation } from '../chat-data';

interface SidebarProps {
  theme: Theme;
  conversations: Conversation[];
  activeId: string;
  collapsed: boolean;
  onSelect: (id: string) => void;
  onNewChat: () => void;
  onToggle: () => void;
}

/**
 * The conversation rail — a thin wrapper over `<kai-conversations>`. The `.sidebar` div
 * owns the shell's right border (kept OFF the element so it follows the shell's
 * light/dark tokens, not the light-mode ones the element pins on itself at `:host`).
 * The rail's `collapsed` is CONTROLLED by the app's collapsed state, so it stays in
 * sync with the parent `<ResizableItem collapsed>` and re-expands the list on restore;
 * `onToggleSidebar` still reports the toggle intent up via `onToggle`.
 */
export function Sidebar({ theme, conversations, activeId, collapsed, onSelect, onNewChat, onToggle }: SidebarProps) {
  return (
    <aside className="sidebar">
      <Conversations
        theme={theme}
        groups={[]} /* flat list: the element buckets `conversations` by recency itself */
        conversations={conversations}
        activeId={activeId}
        collapsed={collapsed}
        onConversationSelect={(e) => onSelect(e.detail.id)}
        onNewChat={onNewChat}
        onToggleSidebar={onToggle}
      />
    </aside>
  );
}

// examples/starters/vue/src/components/Sidebar.vue
<script setup lang="ts">
import type { Theme } from '../types';
import type { Conversation } from '../chat-data';

/**
 * The conversation rail — a thin wrapper over `<kai-conversations>`. The `.sidebar` div
 * owns the shell's right border (kept OFF the element so it follows the shell's
 * light/dark tokens, not the light-mode ones the element pins on itself at `:host`).
 * The rail's `collapsed` is CONTROLLED by the app's collapsed state, so it stays in
 * sync with the parent `<kai-resizable-item collapsed>` and re-expands the list on
 * restore; the internal hamburger still reports the toggle intent up via
 * `@kai-toggle-sidebar`.
 *
 * Array/object props (`groups`, `conversations`) MUST be set as DOM properties, so
 * they use the `.prop` modifier. `activeId` / `collapsed` are scalars.
 */
defineProps<{
  theme: Theme;
  conversations: Conversation[];
  activeId: string;
  collapsed: boolean;
}>();

const emit = defineEmits<{
  select: [id: string];
  newChat: [];
  toggle: [];
}>();

function onSelect(e: Event) {
  emit('select', (e as CustomEvent<{ id: string }>).detail.id);
}
</script>

<template>
  <aside class="sidebar">
    <kai-conversations
      :theme="theme"
      :groups.prop="[]"
      :conversations.prop="conversations"
      :active-id="activeId"
      :collapsed.prop="collapsed"
      @kai-conversation-select="onSelect"
      @kai-new-chat="emit('newChat')"
      @kai-toggle-sidebar="emit('toggle')"
    ></kai-conversations>
  </aside>
</template>
